"""add tools column to requests

Revision ID: 5505052298a3
Revises: b361dfd0079e
Create Date: 2026-03-17 17:49:34.487770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5505052298a3'
down_revision: Union[str, None] = 'b361dfd0079e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('requests', sa.Column('tools', postgresql.ARRAY(sa.Text()), nullable=True))
    op.execute("UPDATE requests SET tools = '{}' WHERE tools IS NULL")
    op.alter_column('requests', 'tools', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'tools')
    # ### end Alembic commands ###
