"""add rating column to outputs

Revision ID: 8133efef1081
Revises: 9674b80d3794
Create Date: 2026-03-17 16:01:39.144356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8133efef1081'
down_revision: Union[str, None] = '9674b80d3794'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outputs', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outputs', 'rating')
    # ### end Alembic commands ###
