"""initial schema

Revision ID: 90af1a305088
Revises: 
Create Date: 2026-03-17 10:12:35.921665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90af1a305088'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_requests_queue', 'requests', ['priority', 'created_at'], unique=False, postgresql_where=sa.text("status = 'queued'"))
    op.create_index('idx_requests_status', 'requests', ['status'], unique=False)
    op.create_index('idx_requests_tags', 'requests', ['tags'], unique=False, postgresql_using='gin')
    op.create_table('outputs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('inference_time_ms', sa.Integer(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('embedding', Vector(1536), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_outputs_request', 'outputs', ['request_id'], unique=False)
    op.create_index('idx_outputs_status', 'outputs', ['status'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('output_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('follow_up_request_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['follow_up_request_id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['output_id'], ['outputs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reviews_output', 'reviews', ['output_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reviews_output', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('idx_outputs_status', table_name='outputs')
    op.drop_index('idx_outputs_request', table_name='outputs')
    op.drop_table('outputs')
    op.drop_index('idx_requests_tags', table_name='requests', postgresql_using='gin')
    op.drop_index('idx_requests_status', table_name='requests')
    op.drop_index('idx_requests_queue', table_name='requests', postgresql_where=sa.text("status = 'queued'"))
    op.drop_table('requests')
    # ### end Alembic commands ###
