"""add truncated column to outputs

Revision ID: 96b41769705c
Revises: 90af1a305088
Create Date: 2026-03-17 12:15:24.844376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96b41769705c'
down_revision: Union[str, None] = '90af1a305088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('outputs', sa.Column('truncated', sa.Boolean(), nullable=True))
    op.execute("UPDATE outputs SET truncated = false WHERE truncated IS NULL")
    op.alter_column('outputs', 'truncated', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outputs', 'truncated')
    # ### end Alembic commands ###
