"""add model_id to requests

Revision ID: b361dfd0079e
Revises: 8133efef1081
Create Date: 2026-03-17 16:32:05.886369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b361dfd0079e'
down_revision: Union[str, None] = '8133efef1081'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('model_id', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'model_id')
    # ### end Alembic commands ###
